# typed: false
# frozen_string_literal: true

# Homebrew formula for the LLM Status CLI (mm). Installs the prebuilt binary —
# Developer ID signed + Apple-notarized on macOS — from cdn.llmstatus.ai.
# Generated by scripts/gen-homebrew-formula.mjs; do not edit by hand.
class ModelstatusCli < Formula
  desc "Track which AI models your codebase uses and their lifecycle"
  homepage "https://llmstatus.ai"
  version "0.1.84"
  license "MIT"

  on_macos do
    on_arm do
      url "https://llmstatus.ai/dl/cli/v0.1.84/modelstatus-cli-darwin-arm64"
      sha256 "dc3a138cefc7e3b280459a3869353900e816942deb9ef7cda2ea7946f7750220"
    end
    on_intel do
      url "https://llmstatus.ai/dl/cli/v0.1.84/modelstatus-cli-darwin-x64"
      sha256 "941906fe09f4cb35818804b47d8da1594bde332c10efc68d91e741ff3a0c0dba"
    end
  end

  on_linux do
    on_arm do
      url "https://llmstatus.ai/dl/cli/v0.1.84/modelstatus-cli-linux-arm64"
      sha256 "8ca8850bb715bb2cbb5867c3971f8a068098bd3e27704f5ef5a7a396039e79a5"
    end
    on_intel do
      url "https://llmstatus.ai/dl/cli/v0.1.84/modelstatus-cli-linux-x64"
      sha256 "897e4f4920b8f62e925418bd082754783a064a85f2162ed62d7c62ba4b63f71e"
    end
  end

  def install
    bin.install Dir["*"].first => "mm"
    bin.install_symlink bin/"mm" => "llmstatus"
  end

  test do
    assert_match "0.1.84", shell_output("#{bin}/mm --version")
  end
end
