# typed: false
# frozen_string_literal: true

# Homebrew formula for the LLM Status CLI (mm). Installs the prebuilt binary —
# Developer ID signed + Apple-notarized on macOS — from cdn.llmstatus.ai.
# Generated by scripts/gen-homebrew-formula.mjs; do not edit by hand.
class ModelstatusCli < Formula
  desc "Track which AI models your codebase uses and their lifecycle"
  homepage "https://llmstatus.ai"
  version "0.1.80"
  license "MIT"

  on_macos do
    on_arm do
      url "https://cdn.llmstatus.ai/cli/v0.1.80/modelstatus-cli-darwin-arm64"
      sha256 "1c590f354f5eebfa0c67d067325f39d9fd08c9e4d5f02a490ea134fedfc9545b"
    end
    on_intel do
      url "https://cdn.llmstatus.ai/cli/v0.1.80/modelstatus-cli-darwin-x64"
      sha256 "e42b841830d24a90689c1b2ebc9a1dbc9cf855a5278fa2bd4e7a38be68f19904"
    end
  end

  on_linux do
    on_arm do
      url "https://cdn.llmstatus.ai/cli/v0.1.80/modelstatus-cli-linux-arm64"
      sha256 "3b7b1e513d5e57ed8124fb13c6f4db6ddb435a7ca58c5bb39f93668c0da703dd"
    end
    on_intel do
      url "https://cdn.llmstatus.ai/cli/v0.1.80/modelstatus-cli-linux-x64"
      sha256 "02674474d2362f5f1a1f935d9a2bbf9fdbdbb2584ba4988a55197d6aac1a2384"
    end
  end

  def install
    bin.install Dir["*"].first => "mm"
    bin.install_symlink bin/"mm" => "llmstatus"
  end

  test do
    assert_match "0.1.80", shell_output("#{bin}/mm --version")
  end
end
