# typed: false
# frozen_string_literal: true

# Homebrew formula for the LLM Status CLI (mm). Installs the prebuilt binary —
# Developer ID signed + Apple-notarized on macOS — from cdn.llmstatus.ai.
# Generated by scripts/gen-homebrew-formula.mjs; do not edit by hand.
class ModelstatusCli < Formula
  desc "Track which AI models your codebase uses and their lifecycle"
  homepage "https://llmstatus.ai"
  version "0.1.78"
  license "MIT"

  on_macos do
    on_arm do
      url "https://cdn.llmstatus.ai/cli/v0.1.78/modelstatus-cli-darwin-arm64"
      sha256 "689ac0ca2bc28e2ce02e20b583f4738cdfdbf74111b8ea982b531ce4596b944a"
    end
    on_intel do
      url "https://cdn.llmstatus.ai/cli/v0.1.78/modelstatus-cli-darwin-x64"
      sha256 "b4e574d2eb0c7d994b2362b96d99a27a7a783f245bdd7202502ef75f1578af8c"
    end
  end

  on_linux do
    on_arm do
      url "https://cdn.llmstatus.ai/cli/v0.1.78/modelstatus-cli-linux-arm64"
      sha256 "84d9f656367e06a88466e221320330119b7249392d39ece97df0c6a7e3cf4f6d"
    end
    on_intel do
      url "https://cdn.llmstatus.ai/cli/v0.1.78/modelstatus-cli-linux-x64"
      sha256 "46eebe308d69248129d320c6215b7e4220cbff19c68ef446050260a1deaba3d0"
    end
  end

  def install
    bin.install Dir["*"].first => "mm"
    bin.install_symlink bin/"mm" => "llmstatus"
  end

  test do
    assert_match "0.1.78", shell_output("#{bin}/mm --version")
  end
end
